[package]
name        = "museum-restaurant"
version     = "2.0.1"
flix        = "0.76.2"
repository  = "github:flix/museum-restaurant"

[mvn-dependencies]
"org.apache.commons:commons-lang3" = "3.12.0"
