[package]
name        = "museum-restaurant"
description = "test"
version     = "1.1.0"
flix        = "0.34.0"
authors     = ["John Doe <john@example.com>"]

[mvn-dependencies]
"org.apache.commons:commons-lang3" = "3.12.0"
